# Generated by Django 4.0.4 on 2022-05-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='book',
            name='desc',
            field=models.TextField(default='暂无简介'),
        ),
        migrations.AddField(
            model_name='book',
            name='image_url',
            field=models.CharField(blank=True, default=None, max_length=228, null=True),
        ),
    ]
