# Generated by Django 4.0.4 on 2022-05-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_user_email_alter_user_name_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='c_time',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32),
        ),
    ]
